# Generated by Django 4.1.5 on 2023-11-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
