# Generated by Django 4.1.5 on 2023-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getintouch",
            name="bg_image",
            field=models.ImageField(blank=True, null=True, upload_to="contact/"),
        ),
    ]
