# Generated by Django 4.1.5 on 2023-11-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_getintouch_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="parking",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
