# Generated by Django 4.1.5 on 2023-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_property_bathrooms_property_parking"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
